### ISSUE TITLE
getting error in digital ocean and heroku

### ISSUE THREAD

**Issue by juanbzz** [jmervine/node-yslowjs#3]
In Heroku and Digital Ocean (using dokku) I get:
`{
error: {
code: "ENOENT",
errno: "ENOENT",
syscall: "spawn"
}
}`

In both cases I have phantomjs and yslow installed, I run `heroku run phantomjs yslow.js --info basic http://mashable.com` and I got the results, in dokku the same and I also get the result, but when using like this: https://github.com/thinkxl/YSlow-node-express-example/blob/master/routes/index.js I got the results above mentioned

**Comment by jmervine** [comment]
> TL;DR quick fix: Ensure that phantomjs at `npm install` time and phantomjs run time are in the exact same location on your host.

Interesting, it looks like you're using a pretty basic example which should use the version of YSlow.js and PhantomJS installed when `node-ypslowjs` is installed. That error (most likely) means that it's not finding phantomjs. The phantomjs path is set an install time, when the dependency [`phapper`](https://www.npmjs.org/package/phapper) is installed. 

The way the phantomjs component of this works is, if checks your `PATH`, if it find it, it writes the path to it in a file, which is then included at run time, otherwise, it installs phantomjs in node_modules and writes the installation path, using that. If you're installing on one machine, and running on another, it's not going to work unless both hosts have phantomjs located in the exact same place. This could be considered a bug, but honestly it's how I designed [`phapper`](perhaps poorly). It's been my intention for some time to port this to use https://www.npmjs.org/package/phantomjs over [`phapper`]. Down side being, phantomjs is always installed by the `phantomjs` NPM, whereas [`phapper`] will use a found installation.

Note to self: Investigate replacing `phapper` with the `phantomjs` NPM, or updating the way `phapper` installs phantomjs (less likely to be viable).

**Comment by juanbzz** [comment]
Thanks for answer, I will check that tonight and get back with the results.

**Comment by jmervine** [comment]
@thinkxl looking at this again, still an issue, long forgotten, somewhere in between? Cheers!

**Comment by jmervine** [comment]
Closing, please feel free to reopen if this issue persists.

**Comment by sudeepdk** [comment]
This will work 100 % -- follow this it worked for me ... 

https://www.vultr.com/docs/how-to-install-phantomjs-on-ubuntu-16-04
